//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carsharingbackend.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverXCar
    {
        public int id { get; set; }
        public int idCar { get; set; }
        public int idDriver { get; set; }
        public System.DateTime lendStartDate { get; set; }
        public System.DateTime lendEndDate { get; set; }
        public bool active { get; set; }
    
        [Newtonsoft.Json.JsonIgnore] public virtual car car { get; set; }
        public virtual driver driver { get; set; }
    }
}
