//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carsharingbackend.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carsharingdbEntities : DbContext
    {
        public carsharingdbEntities()
            : base("name=carsharingdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<car> cars { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<carOwner> carOwners { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<carPosition> carPositions { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<component> components { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<driver> drivers { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<driverXCar> driverXCars { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<notification> notifications { get; set; }
    }
}
