//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carsharingbackend.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int id { get; set; }
        public int idCar { get; set; }
        public int idDriver { get; set; }
        public int idComponent { get; set; }
        public System.DateTime notificationDate { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public bool isThere { get; set; }
        public bool active { get; set; }
    
        public virtual car car { get; set; }
        public virtual component component { get; set; }
        public virtual driver driver { get; set; }
    }
}
